Svelte 5 migration
portabletext/svelte-portabletext pull request #145
Opened 2024-11-09 13:20 UTC by ampled

## Description

This is my attempt to kickstart svelte 5 support. It's probably enough to just allow svelte 5 as a peerDependency considering svelte 5 has backwards compatibility, but I guess it's nice to have this as a starting point for a full migration. 

All tests are passing, though I had to add a line to remove comments from rendered output before comparing it to expected output.

## Changes

- Migrated all Svelte components using 1st party migration script, then cleaning up by hand
- Added recommended svelte testing plugin to vite-config following Testing Library setup guide
- Updated packages required for svelte 5 and getting tests running

2024-11-30 13:25 UTC, TheOnlyTails commented
Would be amazing to see this merged!

2024-12-10 16:02 UTC, ampled commented
@TheOnlyTails 
> Would be amazing to see this merged!

Until then, you can use this: https://www.npmjs.com/package/@eirikk/portabletext-2-svelte-5

Follow the instructions in the README to not have to rewrite any imports

2025-01-02 12:56 UTC, ampled commented
@stipsan looks like the most recent official contributor. Hope it's okay that I tag you to get this looked at ☺️

2025-02-05 19:02 UTC, mikehwagz commented
Anything I can do to help get this merged? It is disappointing that this has taken so long considering Svelte 5 has been out now for a considerable amount of time.

2025-02-06 11:47 UTC, rdunk commented
Hello, we're releasing some significant updates for Svelte shortly. I'll get this reviewed and merged by the end of the week. Thanks for your patience.

2025-02-06 16:14 UTC, rdunk requested changes
Thank you so much for this, I've done an initial pass and it all looks pretty good to me.

I've just made some suggestions to primarily reduce intermediate `$derived` values, but I don't think this is critical. I'm by no means an expert in Svelte's reactivity system so there could be good reason for them, let me know what you think either way and I'll get this approved, merged and released asap.

2025-02-06 16:14 UTC, rdunk commented on tests/render.test.ts
> +    expect(5).toBe(5)
Can this be removed?
```suggestion
```

2025-02-07 10:32 UTC, ampled commented on src/routes/+page.svelte
> +<PortableText bind:this={comp} value={homepage} />
removed

2025-02-07 10:48 UTC, ampled commented
> I've just made some suggestions to primarily reduce intermediate `$derived` values, but I don't think this is critical. I'm by no means an expert in Svelte's reactivity system so there could be good reason for them, let me know what you think either way and I'll get this approved, merged and released asap.

Great! I accepted all suggestions. All the `$derived` values were directly translated from the existing code, taking old "reactive values" like `$: value = portableText.value` and converting them to `let {value} = $derived(portableText)` so no issues with improving on this re: readability ⭐

2025-02-07 11:33 UTC, rdunk commented
Awesome, thank you 🙇 . If you wouldn't mind rebuilding the `package-lock.json` on your branch to resolve the conflicts I'll get this merged and released.

2025-02-07 15:44 UTC, rdunk approved these changes

2025-02-07 15:44 UTC, merged